containerm/ctr/ctr_tls_util.go, containerm/ctr/ctr_tls_util_test.go
[#9] Do not mess with the crypto package definitions and include or exclude specific cyphers. Use the secure cipher suites, returned by tls.CipherSuites(), in TLS configurations for image registries.
=> Filter out insecure cipher suites in TLS configuration.

containerm/ctr/ctrd_client_internal_test.go, containerm/pkg/testutil/matchers/contains_string_matcher.go
[#31] Added test cases for the following internal client's functionalities:
- log driver management (initialization)
- container process termination with and without SIGKILL
- events processing
Added custom Matcher interface for checking whether the actual argument contains the provided string
Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>
=> Ensure containerd's internal client logs, events and process termination handling are unit tested

containerm/ctr/ctrd_client_test.go, containerm/mgr/mgr_test.go, containerm/network/libnet_mgr_test.go, containerm/pkg/testutil/assertions.go, containerm/things/things_containers_service_internal_test.go, containerm/things/things_test_base_test.go
[#34] Provide unit tests for collecting runtime metrics for containerized applications
Provide relevant unit tests for collecting runtime metrics functionality
=> Provide unit tests for collecting runtime metrics for containerized applications

SECURITY.md
[#75] Incorporate the Eclipse security policy
- SECURITY.md initial version
Signed-off-by: Evgeni Grigorov <Evgeni.Grigorov@bosch.io>
=> Eclipse security policy for container management

containerm/events/events.go, containerm/mgr/mgr.go
[#108]Update ctr manager and events manager service identifiers
=> Align service ids

integration/ctr_factory_test.go, integration/ctr_management_suite.go, integration/ctr_management_test_constants.go, integration/ctr_metrics_test.go
[#71] Provide integration tests via the key Ditto features - Metrics
Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>
=> Provide integration tests via the key Ditto features - Metrics

integration/ctr_management_cli_test.go, integration/testdata/create-test.yaml, integration/testdata/logs-test.yaml, integration/testdata/remove-test.yaml, integration/testdata/start-test.yaml, integration/testdata/stop-test.yaml, integration/testdata/update-test.yaml
[#126] Change container names in the CLI IT
Changed the names of the containers created by the integration tests.
Signed-off-by: Daniel Milchev <fixed-term.daniel.milchev@bosch.io>
=> Change container names in the CLI IT

.github/workflows/validation.yaml, integration/testdata/list-help.golden, integration/testdata/list-test.yaml
[#117] Provide integration test for the CLI list command
- provide golden file
- provide yaml file with test scenarios
Signed-off-by: Guzgunova Antonia <Antonia.Guzgunova@bosch.io>
=> Provide integration test for the CLI list command

containerm/cli/cli_command_ctrs_create.go, containerm/daemon/daemon_config.go, containerm/mgr/mgr_internal.go, containerm/mgr/mgr_test.go, containerm/network/libnet_mgr.go, containerm/network/libnet_mgr_init.go, containerm/network/libnet_mgr_internal.go, containerm/network/libnet_mgr_internal_common_ctrs.go, containerm/network/libnet_mgr_test.go, containerm/util/containers.go, integration/testdata/create-help.golden
[#122] Allow the extra_hosts entries to contain other mappings
=> Allow extra hosts entries to contain container mappings

NOTICE.md, go.mod, go.sum
[#131] Update containerd to 1.6.18
=> Bump containerd

integration/framework/cli/cmd_base.go, integration/testdata/create-test.yaml, integration/testdata/list-test.yaml, integration/testdata/logs-test.yaml, integration/testdata/remove-test.yaml, integration/testdata/start-test.yaml, integration/testdata/stop-test.yaml, integration/testdata/sysinfo-test.yaml, integration/testdata/update-test.yaml
[#134 ] [CLI IT] Force stop containers to ensure no flakes in the tests
=> Force stop containers to ensure no flakes in the tests

containerm/ctr/ctrd_decrypt_mgr.go
[#161] Error while trying to create container on raspberry pi
Default to fallback platform match when a multi-arch container image is authorized by imgcrypt library.
=> Error while trying to create container on raspberry pi

containerm/cli/cli_commamd_ctrs_base_test.go, containerm/cli/cli_command_ctrs_create.go, containerm/cli/cli_command_ctrs_create_test.go, containerm/util/containers_parse.go, containerm/util/containers_parse_test.go, containerm/util/containers_validation.go, containerm/util/containers_validation_test.go, containerm/util/util_base_test.go
[#176] Preparation for implementing apply of desired state for containers update agent
Some preparation work before the real implementation:
- move parse functions from cli main package to common containerm/util package, to be used also by container update agent implementation, updated error messages to be more informative and show the problem
- added additional validation for container - cannot have a privileged container with specified devices
Signed-off-by: Stoyan Zoubev <Stoyan.Zoubev@bosch.io>
=> Preparation for implementing apply of containers desired state

containerm/daemon/daemon_test.go, containerm/updateagent/internal_desired_state.go, containerm/updateagent/to_containers.go, containerm/updateagent/update_manager.go, containerm/updateagent/update_manager_util.go, containerm/updateagent/update_manager_util_test.go, containerm/updateagent/update_operation.go, containerm/util/containers_compare.go
[#166] Implement apply of desired state for containers update agent
Signed-off-by: Stoyan Zoubev Stoyan.Zoubev@bosch.io
=> Implement apply of desired state for containers update agent

NOTICE.md
[#189] Change golang/x/term version in NOTICE.md
=> Change golang/x/term version in NOTICE.md

NOTICE.md, go.mod, go.sum
[#206] Upgraded the needed dependency to the latest version.
=> Upgrade google.golang.org/grpc to the latest version.

containerm/updateagent/update_manager_test.go, containerm/updateagent/update_operation.go, containerm/updateagent/update_operation_test.go
[#201] Optimized, deterministic intermediate desired state feedback messages from update agent
- added unit tests for update agent command processing and feedback messages
Signed-off-by: Stoyan Zoubev <Stoyan.Zoubev@bosch.io>
=> [#201] Optimized, deterministic intermediate desired state feedback messages

.github/workflows/validation.yaml, containerm/daemon/daemon_internal.go
[#191] Container remains Stopped after container-management service restart
=> Rearrange daemon startup sequence

README.md
[#226] Changed functionality of logo to open the main page of the site. Changed functionality of badge to not open a picture of itself.
Signed-off-by: Daniel Milchev [fixed-term.daniel.milchev@bosch.io](mailto:fixed-term.daniel.milchev@bosch.io)
=> Changed functionality of logo and badge.

containerm/mgr/mgr_internal_init.go, containerm/updateagent/update_operation.go
[#236] CUA allow rollback when owner denies update
Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.com>
=> CUA allow rollback when owner denies update

integration/testdata/remove-help.golden, integration/testdata/stop-help.golden
[#238] Set correct timeout flag in integration tests
Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>
=> [#238] Set correct timeout flag in integration tests
