eclipse-kanto/container-management

containerm/things/datatypes_container_configuration.go
containerm/things/datatypes_container_configuration_test.go
containerm/things/features_container.go
containerm/things/features_container_factory.go

[#6] The root process arguments per container are now available for configuration via the Ditto API.
Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

Root process arguments available for configuration remotely

---

containerm/ctr/ctrd_registries_resolver.go
containerm/ctr/ctrd_registries_resolver_test.go

[#15] Provide unit TCs for container image registry resolver
The provided TCs cover the related implementation and additional optimizations are done based on the code analysis done to write the TCs.
Signed-off-by: Antonia Trifonova <Antonia.Trifonova@bosch.io>

Provide unit TCs for container image registry resolver

---

NOTICE.md
containerm/containers/types/host_config.go
containerm/ctr/ctr_client_opts.go
containerm/ctr/ctrd_client.go
containerm/ctr/ctrd_client_init.go
containerm/ctr/ctrd_client_internal.go
containerm/ctr/ctrd_container_create_opts.go
containerm/ctr/ctrd_oci_linux.go
containerm/daemon/daemon_command.go
containerm/daemon/daemon_config.go
containerm/daemon/daemon_config_default.go
containerm/daemon/daemon_config_util.go
containerm/daemon/daemon_test.go
containerm/mgr/mgr.go
containerm/pkg/testutil/config/daemon-config.json
containerm/util/containers.go
containerm/util/protobuf/convert_to_internal_util.go
containerm/util/protobuf/convert_to_proto_util.go
containerm/util/util_system.go

[#25] Support for cgroups v2
- use io.containerd.runc.v2 by default
- configurable runc runtime upon daemon start
- use systemd cgroup driver

Support for cgroups v2

---

containerm/mgr/container_fs_repository.go
containerm/mgr/mgr.go

[#13] Irrelevant warning when starting container daemon
The irrelevant warning is removed.
Signed-off-by: Antonia Trifonova <Antonia.Trifonova@bosch.io>

Warning when starting container daemon

---

containerm/ctr/ctrd_client_internal.go
containerm/ctr/ctrd_client_internal_test.go
containerm/ctr/ctrd_client_test.go
containerm/pkg/testutil/matchers/cio_attach_matcher.go
containerm/pkg/testutil/matchers/cio_creator_matcher.go
containerm/pkg/testutil/matchers/kill_task_opts_matcher.go

[#24] Cover the internal client's respective functionality with appropriate TC.
Added test cases for the following internal client's functionalities:
- generate remote, unpack and new container options
- get and pull image
- create and clear snapshot
- create and load task
Added custom matchers for cio attach, cio creator and kill task opts.
Updated new container opts matcher.
Signed-off-by: Gabriela Yoncheva <Gabriela.Yoncheva@bosch.io>

Provide Unit TC for the containerd internal client implementation

---

containerm/resources/container-management.service

[#39] Install to /usr/bin
libostree requires all binaries installed using rpm to be in `/usr/bin` rather than `/usr/local/bin`

Install to /usr/bin

---

containerm/ctr/ctr_client_opts.go
containerm/ctr/ctr_client_opts_test.go
containerm/ctr/ctrd_client_init.go
containerm/ctr/ctrd_spi.go
containerm/ctr/ctrd_spi_events_test.go
containerm/ctr/ctrd_spi_images_test.go
containerm/ctr/ctrd_spi_snapshots_test.go
containerm/daemon/daemon_command.go
containerm/daemon/daemon_config.go
containerm/daemon/daemon_config_default.go
containerm/daemon/daemon_config_util.go
containerm/daemon/daemon_test.go
containerm/pkg/testutil/config/daemon-config.json

[#38] Make the container management lease ID configurable
- add daemon flag --ccl-lease-id
- add unit tests

Make the container management lease ID configurable

---

NOTICE.md
go.mod
go.sum

[#56] container-management_git.bb:do_compile failed with exit code '1' for amd64
Updated to the first stable version where the assembler issue is fixed in github.com/klauspost/compress - v1.13.6
Signed-off-by: Konstantina Gramatova <konstantina.gramatova@bosch.io>

Bump github.com/klauspost/compress to v1.13.6 

---

CODE_OF_CONDUCT.md

[#77] Incorporate the Eclipse code of conduct
- CODE_OF_CONDUCT.md initial version
Signed-off-by: Evgeni Grigorov <Evgeni.Grigorov@bosch.io>

Eclipse code of conduct for container management

---

containerm/cli/cli_config.go
containerm/cli/cli_test.go

[#83] Flags --host and --debug should be global
- Flags `--host` and `--debug` are now inherited by all child commands of `kanto-cm`
- The flags can be seen when you list the help commands under `Global Flags`.
Signed-off-by: Kristiyan Gostev [kristiyan.gostev@bosch.io](mailto:kristiyan.gostev@bosch.io)

Expose flags --host and --debug to all child commands

---

containerm/cli/cli.go
containerm/cli/cli_config.go
containerm/cli/cli_test.go
containerm/client/client_init.go

[#84] TCP Protocol is not supported by kanto-cm when using the --host flag
- the behaviour to default to `unix` is still preserved
- the deprecated `grpc.Dial` method is replaced with `grpc.DialContext`
- `WithBlock()` option is added so we can benefit from the context timeout
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

Add support for TCP protocol when using --host flag

---

containerm/daemon/daemon_start.go
containerm/mgr/mgr_internal_init.go
containerm/network/libnet_mgr_init.go
containerm/network/libnet_mgr_init_test.go
containerm/server/grpc_server_internal_init.go
containerm/server/grpc_server_internal_init_test.go
containerm/things/features_rollouts_software_updatable_internal_test.go
containerm/things/things_containers_service_init.go
containerm/things/things_containers_service_internal_test.go
containerm/things/things_containers_service_test.go
containerm/things/things_test_base_test.go

[#100] Unable to create lock file at /run/container-management/lock Error: no such file or directory
- Ensure that all necessary directories that are configured exists
- Lock file is now created in more suitable directory 
Signed-off-by: Kristiyan Gostev <kristiyan.gostev@bosch.io>

Directory handling improvements on daemon start

---

containerm/things/features_container_factory.go
containerm/things/features_container_factory_test.go
integration/ctr_management_suite.go

[#104] ContainerFactory feature is not compliant with the Vorto model
- fix create and createWithConfig operations are fixed to return the ID of the created container instance
- unit tests are fixed with these changes
- integration tests are fixed these changes
Signed-off-by: Guzgunova Antonia <Antonia.Guzgunova@bosch.io>

ContainerFactory feature is not compliant with the Vorto model

---

integration/ctr_management_cli_test.go
integration/testdata/remove-help.golden
integration/testdata/remove-test.yaml
integration/testdata/start-help.golden
integration/testdata/start-test.yaml
integration/testdata/stop-help.golden
integration/testdata/stop-test.yaml

[#116] Provide integration test for the CLI start, stop and remove commands
- In addition, test for `kanto-cm -h` is also added

Provide integration test for the CLI start, stop and remove commands

---

integration/framework/cli/cmd_base.go
integration/framework/cli/cmd_base_api.go
integration/framework/cli/cmd_base_custom_result.go
integration/testdata/logs-help.golden
integration/testdata/logs-test.yaml
integration/testdata/sysinfo-help.golden
integration/testdata/sysinfo-test.yaml
integration/testdata/update-help.golden
integration/testdata/update-test.yaml

[#119] Provide integration test for the CLI sysinfo, logs and update commands
- added integration tests for sysinfo, update and logs CLI commands
- implemented custom result function for logs command
- fixed stop_invalid_id test

Provide integration test for the CLI sysinfo, logs and update commands

---

integration/ctr_instance_test.go
integration/ctr_management_suite.go
integration/ctr_management_test_constants.go

[#63] Provided integration tests via the key Ditto features - Container per instance
Covered operations of the container instance: start, stop, pause, resume, rename, remove, stopWithOptions, update
Signed-off-by: Ognian Baruh <Ognyan.Baruh@bosch.io>

Provided integration tests via the key Ditto features - Container per instance

---

integration/ctr_management_cli_test.go
integration/framework/cli/cmd_base.go
integration/testdata/get-help.golden
integration/testdata/get-test.yaml

[#118] Provide integration test for the CLI get command
Created golden file and test case scenarios with exit code 1.
Signed-off-by: Daniel Milchev <fixed-term.daniel.milchev@bosch.io>

Provide integration test for the CLI get command

---

NOTICE.md
go.mod
go.sum

[#142] Opencontainers runc Incorrect Authorization vulnerability

Bump opencontainers/runc to version 1.1.5

---

containerm/daemon/daemon_command.go
containerm/daemon/daemon_config.go
containerm/daemon/daemon_config_default.go
containerm/daemon/daemon_config_util.go
containerm/daemon/daemon_internal.go
containerm/daemon/daemon_internal_init.go
containerm/daemon/daemon_test.go
containerm/deployment/deployment.go
containerm/deployment/deployment_api.go
containerm/deployment/deployment_internal.go
containerm/deployment/deployment_internal_init.go
containerm/deployment/deployment_opts.go
containerm/deployment/deployment_opts_test.go
containerm/deployment/deployment_test.go
containerm/pkg/testutil/config/container/nested/container-config.json
containerm/pkg/testutil/config/container/valid.json
containerm/pkg/testutil/config/daemon-config.json
containerm/pkg/testutil/matchers/container_image_matcher.go
containerm/util/containers.go
containerm/util/containers_compare.go
containerm/util/containers_compare_test.go
containerm/util/containers_test.go

[#148] Implement automated update of containers
- Updated DeploymentConfig structure: added enable option (true/false), added mode option (init/update), renamed init_dir option to ctr_dir.
- Implemented comparison between an existing container and a desired one. Result of comparison is action to be done in order to achieve desired state.
- Rename InitialDeploy method to Deploy only.
- Implemented logic for automated update of containers via descriptor files.
- Added unit tests to cover updating containers by Deployment Manager service.
Signed-off-by: [Stoyan.Zoubev@bosch.io](mailto:Stoyan.Zoubev@bosch.io)

Implemented automated update of containers via descriptor files

---

go.mod

[#151] Bump the minimal go version in go.mod
- set minimal go version to 1.19

Set the minimal go version to 1.19 in go.mod

---

containerm/ctr/ctrd_container_create_opts.go

[#153] Not all capabilities are applied when using --privileged flag

Add privileged option to the container spec

---

containerm/things/features_container_factory_event_handler.go
containerm/things/features_container_factory_event_handler_test.go

[#157]  Container status is updated to dead after the container is deleted

Container status is updated to dead after the container is deleted

---

containerm/deployment/deployment_internal.go
containerm/deployment/deployment_test.go

[#159] Auto deployed container remains stopped after an update

Ensure that container is running after an update without re-creation

---

containerm/daemon/daemon_command.go
containerm/daemon/daemon_config.go
containerm/daemon/daemon_config_default.go
containerm/daemon/daemon_config_util.go
containerm/daemon/daemon_test.go
containerm/pkg/testutil/config/daemon-config.json

[#169] Local communication properties should be outside of the things service

Move local communication properties outside of the things service

---

containerm/daemon/daemon_command.go
containerm/daemon/daemon_config.go
containerm/daemon/daemon_config_default.go
containerm/daemon/daemon_config_util.go
containerm/daemon/daemon_internal.go
containerm/daemon/daemon_internal_init.go
containerm/daemon/daemon_test.go
containerm/pkg/testutil/config/daemon-config.json
containerm/registry/registry.go
containerm/updateagent/update_agent_init.go
containerm/updateagent/update_agent_opts.go
containerm/updateagent/update_agent_service.go
containerm/updateagent/update_manager.go
containerm/updateagent/update_operation.go
go.mod
go.sum

[#165] Extend daemon configuration with settings for update agent
Dummy implementation of Containers UpdateAgent as Kanto container-management internal service.
- Added UpdateAgentConfig struct, flags and opts for internal containers UpdateAgent service.
- UpdateAgent not fully implemented, just the skeleton. Working implementation will follow with PRs.
Signed-off-by: Stoyan Zoubev [Stoyan.Zoubev@bosch.io](mailto:Stoyan.Zoubev@bosch.io)

Extend daemon configuration and dummy implementation for update agent

---

containerm/updateagent/from_containers.go
containerm/updateagent/from_containers_test.go
containerm/updateagent/update_manager.go
containerm/util/containers_parse.go
containerm/util/containers_parse_test.go

[#167] Implement current state reporting for containers update agent
Also added xxxToString functions next to the available ParseXXX functions for containers device mappings, port mappings, mount points.
Signed-off-by: Stoyan Zoubev <Stoyan.Zoubev@bosch.io>

Implement current state reporting for containers update agent

---

containerm/things/features_rollouts_software_updatable_internal.go
containerm/things/features_rollouts_software_updatable_internal_test.go
integration/ctr_instance_test.go
integration/ctr_management_suite.go
integration/ctr_software_updatable_test.go

[#65] Provide integration tests via the key Ditto features - SoftwareUpdatable
Signed-off-by: Antonia Avramova <antonia.avramova@bosch.io>

Provide integration tests via the key Ditto features - SoftwareUpdatable

---

containerm/ctr/ctrd_checkpoint.go
containerm/ctr/ctrd_cio_mgr_internal.go
containerm/ctr/ctrd_client_internal_test.go
containerm/ctr/ctrd_client_test.go
containerm/ctr/ctrd_container_create_opts_test.go

[#51] Improve containerd client unit tests

Improve containerd client unit tests

---

containerm/cli/cli_command_ctrs_create.go
containerm/cli/cli_command_ctrs_create_test.go
integration/ctr_management_cli_test.go
integration/testdata/container.json
integration/testdata/create-help.golden
integration/testdata/create-test.yaml

[#208] Added the file flag. Added unit and integration tests for it.
Signed-off-by: Daniel Milchev [fixed-term.daniel.milchev@bosch.io](mailto:fixed-term.daniel.milchev@bosch.io)

Add file flag to the CLI create command

---

containerm/cli/cli_command_ctrs_remove.go
containerm/cli/cli_command_ctrs_remove_test.go
containerm/util/cli/args_util.go
containerm/util/error/error_util.go
integration/testdata/remove-help.golden

[#210] Changed remove command to accept more than one container.

Remove command should accept more than one container ID

---

containerm/mgr/mgr.go
containerm/mgr/mgr_internal.go

[#196] Starting of constantly restarting container fails
- Do not release container resources when restart manager is canceled, they are already released upon exit.
- Apply restart policy when it is updated.
Signed-off-by: Dimitar Dimitrov <dimitar.dimitrov3@bosch.com>

Starting of constantly restarting container fails

---

containerm/cli/cli_command_ctrs_list.go
containerm/cli/cli_command_ctrs_list_test.go
containerm/cli/cli_command_ctrs_stop.go
containerm/cli/cli_command_ctrs_stop_test.go
integration/framework/cli/cmd_base.go
integration/testdata/list-help.golden
integration/testdata/list-test.yaml
integration/testdata/remove-test.yaml
integration/testdata/stop-help.golden
integration/testdata/stop-test.yaml

[#213] Add quiet flag, to the list command

Filter and quiet flag for list CLI command.

---

containerm/cli/cli_command_ctrs_create.go
containerm/deployment/deployment.go
containerm/deployment/deployment_test.go
containerm/pkg/testutil/config/container/non_json_files/file1.txt

Deployment only out of .json files #222 Bug Fix

Deployment only out of .json files #222 Bug Fix
